{
 "title": "Benchmark - NodeJS, Golang",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  { "title": "Resource Utilization", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "NodeJS - Memory Usage (in MB):",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "process_resident_memory_bytes{language=\"nodejs\"} / 1024 / 1024",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Golang - Memory Usage (in MB)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "targets": [
    {
     "expr": "process_resident_memory_bytes{language=\"golang\"} / 1024 / 1024",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "NodeJS - CPU Usage Across All Cores (Multiprocessing):",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "sum by(instance) (rate(process_cpu_seconds_total{language=\"nodejs\"}[1m])) * 100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU Usage Across All Cores (Multiprocessing)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "targets": [
    {
     "expr": "sum by(instance) (rate(process_cpu_seconds_total{language=\"golang\"}[1m])) * 100",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Error Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 } },
  {
   "title": "NodeJS - Message Errors Rate (per minute):",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
   "targets": [
    {
     "expr": "rate(websocket_message_errors_total{language=\"nodejs\"}[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Message Errors Rate (per minute)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
   "targets": [
    {
     "expr": "rate(websocket_message_errors_total{language=\"golang\"}[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "NodeJS - Websocket Connection Errors:",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 26 },
   "targets": [
    {
     "expr": "websocket_connection_errors_total{language=\"nodejs\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Websocket Connection Errors",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 26 },
   "targets": [
    {
     "expr": "websocket_connection_errors_total{language=\"golang\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Success Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 34 } },
  {
   "title": "NodeJS - Server Response Time (99th Percentile):",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 35 },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(websocket_server_response_time_seconds_bucket{language=\"nodejs\"}[5m])) by (le))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Server Response Time (99th Percentile)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 35 },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(websocket_server_response_time_seconds_bucket{language=\"golang\"}[5m])) by (le))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "NodeJS - Messages Sent Rate (per minute):",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 43 },
   "targets": [
    {
     "expr": "rate(websocket_messages_sent_total{language=\"nodejs\"}[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Messages Sent Rate (per minute)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 43 },
   "targets": [
    {
     "expr": "rate(websocket_messages_sent_total{language=\"golang\"}[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "NodeJS - Messages Received Rate (per minute):",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 51 },
   "targets": [
    {
     "expr": "rate(websocket_messages_received_total{language=\"nodejs\"}[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Messages Received Rate (per minute)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 51 },
   "targets": [
    {
     "expr": "rate(websocket_messages_received_total{language=\"golang\"}[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "NodeJS - Active WebSocket Connections:",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 59 },
   "targets": [
    {
     "expr": "websocket_active_connections{language=\"nodejs\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Active WebSocket Connections:",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 59 },
   "targets": [
    {
     "expr": "websocket_active_connections{language=\"golang\"}",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}